//! bba — sequential Gröbner-basis driver.
//!
//! Public entry point: [`compute_gb`]. Given an input ideal as a
//! `Vec<Poly>`, it computes the reduced Gröbner basis and returns it
//! in a deterministic, canonical order (ascending by leading
//! monomial under the ring's degrevlex — matches Singular's
//! `sort(G)[1]` convention so the text fixtures compare cleanly).
//!
//! The algorithm is the classical Buchberger loop with Gebauer–Möller
//! pair criteria, using the data structures already in the crate:
//! [`SBasis`] for the growing basis, [`LSet`] for the pair queue, the
//! `gm` module for `enter_s` / `enterpairs`, [`LObject`] as the
//! reducer transient, and the geobucket [`KBucket`] inside the
//! LObject.
//!
//! Reference: `~/Singular/kernel/GBEngine/kstd2.cc`'s `bba()` for the
//! serial homogeneous path, and `redtailBba` for the tail-reduction
//! pass. No code copied; algorithms re-derived.
//!
//! Scope: single-threaded, degrevlex only, `redHomog` semantics. No
//! ecart, no Mora, no signature-based reduction. Output is **the**
//! reduced Gröbner basis — unique up to permutation, and the
//! canonical sort at the end makes the permutation deterministic too.

use std::sync::Arc;

use crate::field::Coeff;
use crate::gm::enterpairs;
use crate::kbucket::KBucket;
use crate::lobject::LObject;
use crate::lset::LSet;
use crate::poly::Poly;
use crate::ring::Ring;
use crate::sbasis::SBasis;

/// Compute the reduced Gröbner basis of the ideal generated by
/// `input`, over the ring `ring`.
///
/// * Zero polynomials in `input` are discarded.
/// * An input containing a nonzero constant collapses to `[1]`.
/// * The returned list is in canonical order: **ascending** by
///   leading monomial under the ring's ordering. This makes the
///   output a deterministic function of the ideal, independent of
///   the order in which generators appear in `input`.
///
/// Thread count: controlled by the `RUSTGB_THREADS` environment
/// variable. Default 1 (serial path). Values `>= 2` dispatch to
/// [`crate::parallel::compute_gb_parallel`], which runs a
/// continuous-cursor sweep with worker-side drain.
///
/// At `T == 1` this runs the serial path, which is deterministic
/// bit-for-bit (matches pre-parallel behaviour). At `T > 1` the
/// output is still the reduced Gröbner basis — unique up to
/// permutation — and the canonical sort removes the permutation
/// ambiguity, so the output is still a function of the ideal.
pub fn compute_gb(ring: Arc<Ring>, input: Vec<Poly>) -> Vec<Poly> {
    let num_threads = rustgb_threads();
    if num_threads == 1 {
        compute_gb_serial(ring, input)
    } else {
        // Cancellation at the env-var-level dispatch surface has no
        // handle caller — we `expect` the computation to complete.
        // For cancellation via an external signal, callers should
        // use `parallel::compute_gb_parallel` directly with their
        // own `Computation` instance (forthcoming work once the FFI
        // cancel hook lands).
        crate::parallel::compute_gb_parallel(ring, input, num_threads)
            .expect("compute_gb cancelled with no external cancel source")
    }
}

/// Parse `RUSTGB_THREADS` from the environment. Default 1. Any
/// non-numeric or negative value parses to 1. Cap at 256 so a user
/// typo (`RUSTGB_THREADS=1000000`) doesn't explode the thread pool.
fn rustgb_threads() -> usize {
    match std::env::var("RUSTGB_THREADS") {
        Ok(v) => v.parse::<usize>().unwrap_or(1).clamp(1, 256),
        Err(_) => 1,
    }
}

/// The serial implementation of `compute_gb`. Exposed so the
/// env-var dispatch can pick between serial and parallel without
/// changing the public API.
pub fn compute_gb_serial(ring: Arc<Ring>, input: Vec<Poly>) -> Vec<Poly> {
    let mut s_basis = SBasis::new();
    let mut l_set = LSet::new();
    let mut next_arrival: u64 = 0;

    // Seed: reduce each nonzero input against the already-accepted
    // basis (so its leading term isn't already covered), make monic,
    // and feed it through the pipeline.
    //
    // Without this pre-reduction pass, redundant input generators
    // (e.g. f_1 = xy+yz+zx when f_0 = x+y+z is already in the
    // basis — x | xy) would stay in the basis all the way to the
    // end, because the SBasis redundancy marking only triggers when
    // the *newer* element's LM divides an older one, not vice versa.
    // Singular's bba() pre-reduces inputs via the same reducer loop.
    for p in input {
        if p.is_zero() {
            continue;
        }
        let sugar = p.lm_deg();
        let mut lobj = LObject::from_poly_with_sugar(Arc::clone(&ring), p, sugar);
        reduce_lobject(&mut lobj, &s_basis, &ring);
        if lobj.is_zero() {
            continue;
        }
        let h_sugar = lobj.sugar();
        let h = lobj
            .into_poly()
            .monic(&ring)
            .expect("nonzero poly has invertible lc");
        next_arrival = insert_and_generate_pairs_with_sugar(
            &ring,
            &mut s_basis,
            &mut l_set,
            h,
            h_sugar,
            next_arrival,
        );
    }

    // Main loop: pop pairs, reduce, insert survivors.
    //
    // Note: we DO NOT skip pairs where an index is redundant. The
    // pair's S-polynomial is still meaningful — the fact that
    // `S[i]`'s leading monomial is divisible by some later element's
    // LM doesn't make the S-pair vanish, it just means the reducer
    // will find a divisor on the first step and start reducing.
    // Singular's `bba()` skips a pair only when its polynomial was
    // physically deleted; our design preserves pointers, so there's
    // nothing to skip here.
    while let Some(pair) = l_set.pop() {
        let s_i = s_basis.poly(pair.i as usize);
        let s_j = s_basis.poly(pair.j as usize);
        let mut lobj = match LObject::from_spoly(Arc::clone(&ring), s_i, s_j, &pair) {
            Some(l) => l,
            None => continue,
        };
        reduce_lobject(&mut lobj, &s_basis, &ring);
        if lobj.is_zero() {
            continue;
        }
        let h_sugar = lobj.sugar();
        let h = lobj
            .into_poly()
            .monic(&ring)
            .expect("nonzero lobject has invertible lc");
        next_arrival = insert_and_generate_pairs_with_sugar(
            &ring,
            &mut s_basis,
            &mut l_set,
            h,
            h_sugar,
            next_arrival,
        );
    }

    // Tail-reduce every surviving basis element against the rest of
    // the basis to obtain the unique reduced GB.
    tail_reduce_all(&mut s_basis, &ring);

    // Extract the surviving (non-redundant) polynomials, canonically
    // sorted. We sort **ascending** by leading monomial to match
    // Singular's `sort(G)[1]` convention (which "smaller polys come
    // first" calls out — the fixture files are in this order too).
    let mut out: Vec<Poly> = s_basis.iter_active().map(|(_, p)| p.clone()).collect();
    out.sort_by(|a, b| {
        let lm_a = a.leading().expect("active basis element is nonzero").1;
        let lm_b = b.leading().expect("active basis element is nonzero").1;
        lm_a.cmp(lm_b, &ring)
    });
    out
}

/// Insert `h` into `s_basis` with an explicit sugar, then run the
/// full `enterpairs` pipeline (pair generation + chain criterion +
/// merge into L). Returns the updated `next_arrival`.
///
/// Important sequencing: `insert_no_clear` runs first, then
/// `enterpairs` (which can now see every not-yet-redundant older
/// element), then `clear_redundant_for` runs to mark older LMs that
/// `h`'s LM divides as redundant. This matches Singular's
/// `initenterpairs` + `clearS` ordering in `kutil.cc::enterpairs`.
/// Reversing the order would suppress pairs against siblings that
/// `h` is about to make redundant, losing relations that the bba
/// would otherwise produce.
///
/// Pairs in L that reference a now-redundant index are *not*
/// purged. They stay in L and are still popped. The main-loop
/// reducer handles them correctly: the first reduction step will
/// find the dividing element (which just arrived) and reduce the
/// leader through it, so the pair still produces the right
/// reduction. See the comment in `compute_gb`'s main loop for why
/// this is the right contract.
fn insert_and_generate_pairs_with_sugar(
    ring: &Ring,
    s_basis: &mut SBasis,
    l_set: &mut LSet,
    h: Poly,
    sugar: u32,
    next_arrival: u64,
) -> u64 {
    let h_idx = s_basis.insert_no_clear(h) as u32;
    let h_ref = s_basis.poly(h_idx as usize);
    let created = enterpairs(ring, s_basis, h_idx, h_ref, sugar, l_set, next_arrival);
    s_basis.clear_redundant_for(ring, h_idx as usize);
    next_arrival + created as u64
}

/// Reduce `lobj` against `s_basis` until no basis element's leading
/// monomial divides the current leader. First-divisor-wins with a
/// sev pre-filter (same pattern as Singular's `kFindDivisibleByInS`).
///
/// Sugar is tracked: after reducing by `s_basis[idx]` with multiplier
/// `m`, the LObject's sugar becomes
/// `max(old_sugar, lm_deg(s_basis[idx]) + deg(m))`.
fn reduce_lobject(lobj: &mut LObject, s_basis: &SBasis, ring: &Arc<Ring>) {
    loop {
        if lobj.is_zero() {
            return;
        }
        // Take a snapshot of the leading monomial & coeff to drive
        // the divisor search.
        let lm_sev = lobj.lm_sev();
        let lm_coeff = lobj.lm_coeff();
        // `lobj.leading()` borrows the bucket mutably — we need to
        // collect the monomial value before running the divisor
        // search over the S-basis.
        let lm = lobj
            .leading()
            .expect("non-zero lobject has leading")
            .1
            .clone();

        let Some(idx) = find_divisor_idx(s_basis, lm_sev, &lm, ring) else {
            return;
        };

        // Perform the reduction step `lobj -= (lm_coeff / s_lc) * m * s`.
        // Every basis element was `monic()`-normalised at insert time,
        // so `s_lc == 1` and `inv_s_lc == 1`; we can skip the Fermat
        // inversion entirely. `c` is just the LObject's leading
        // coefficient.
        let s = s_basis.poly(idx);
        let (s_lc, s_lm_ref) = s.leading().expect("non-redundant basis is nonzero");
        debug_assert_eq!(s_lc, 1, "basis element should be monic");
        let _ = s_lc;
        let m = lm
            .div(s_lm_ref, ring)
            .expect("divisibility already checked");
        let m_deg = m.total_deg();
        let c = lm_coeff;

        lobj.bucket_mut().minus_m_mult_p(&m, c, s);
        lobj.refresh();

        // Sugar update: max(old, sugar(s) + deg(m)). For this driver
        // we use lm_deg(s) as the basis element's sugar. Propagate
        // via `set_sugar`.
        let s_sugar = s_basis.lm_degs()[idx];
        let new_sugar = lobj.sugar().max(s_sugar + m_deg);
        lobj.set_sugar(new_sugar);
    }
}

/// Find the index of a basis element whose leading monomial divides
/// `lm`, skipping redundant entries. Returns the first match in
/// insertion order, or `None`.
///
/// Internally dispatches to a SIMD-batched sev pre-filter when AVX2
/// is enabled at compile time, and a scalar walk otherwise. The two
/// paths produce identical results on identical inputs (verified by
/// `find_divisor_idx_simd_matches_scalar` in the unit tests).
///
/// See `~/rustgb/docs/design-decisions.md` ADR-007 for the rationale.
#[inline]
fn find_divisor_idx(
    s_basis: &SBasis,
    lm_sev: u64,
    lm: &crate::monomial::Monomial,
    ring: &Ring,
) -> Option<usize> {
    let sevs = s_basis.sevs();
    let redund = s_basis.redundant_flags();
    let len = sevs.len();
    let not_lm_sev = !lm_sev;

    let mut idx = 0;
    while idx < len {
        // Find the next sev that passes the pre-filter
        // (`(sevs[idx] & not_lm_sev) == 0`). Returns `len` if none.
        idx = find_sev_match(sevs, not_lm_sev, idx);
        if idx >= len {
            return None;
        }
        // Sev passes; now check redundant flag and the actual divides.
        // Mirror Singular's pattern (kSevScanAVX2 returns a candidate
        // index, the caller does the redund + divides check).
        if !redund[idx] {
            let s_lm = s_basis
                .poly(idx)
                .leading()
                .expect("non-redundant basis element is nonzero")
                .1;
            if s_lm.divides(lm, ring) {
                return Some(idx);
            }
        }
        idx += 1;
    }
    None
}

/// Return the smallest index `i >= start` with
/// `(sevs[i] & not_sev) == 0`, or `sevs.len()` if no such index exists.
///
/// AVX2 path: 16-entry-per-iteration unrolled main loop, mirroring
/// Singular's `kSevScanAVX2`. Falls back to a scalar walk when AVX2
/// is not enabled at compile time.
#[cfg(target_feature = "avx2")]
#[inline]
fn find_sev_match(sevs: &[u64], not_sev: u64, start: usize) -> usize {
    // SAFETY: caller passes a valid slice; we bounds-check every load
    // against `len` before issuing it.
    unsafe { find_sev_match_avx2(sevs, not_sev, start) }
}

#[cfg(not(target_feature = "avx2"))]
#[inline]
fn find_sev_match(sevs: &[u64], not_sev: u64, start: usize) -> usize {
    find_sev_match_scalar(sevs, not_sev, start)
}

/// Scalar implementation of [`find_sev_match`]. Used as the
/// non-AVX2 build path and as the reference for unit tests of the
/// AVX2 path.
#[inline]
fn find_sev_match_scalar(sevs: &[u64], not_sev: u64, start: usize) -> usize {
    let len = sevs.len();
    let mut idx = start;
    while idx < len {
        if (sevs[idx] & not_sev) == 0 {
            return idx;
        }
        idx += 1;
    }
    len
}

/// AVX2 implementation of [`find_sev_match`]. Mirrors Singular's
/// `kSevScanAVX2` (`~/Singular-next-opt/kernel/GBEngine/kstd2.cc:74`).
///
/// # Safety
/// Requires AVX2 available at runtime. Guaranteed by the
/// `cfg(target_feature = "avx2")` gate on the caller. All loads are
/// bounds-checked against `sevs.len()` before being issued.
#[cfg(target_feature = "avx2")]
#[target_feature(enable = "avx2")]
#[inline]
unsafe fn find_sev_match_avx2(sevs: &[u64], not_sev: u64, start: usize) -> usize {
    use std::arch::x86_64::*;
    let len = sevs.len();
    let mut j = start;
    let ptr = sevs.as_ptr();

    // SAFETY of all the unsafe blocks below: every load is bounded
    // by the surrounding `while j + N < len` check before issuing,
    // so the AVX2 256-bit loads stay inside the slice.
    unsafe {
        let vnot_sev = _mm256_set1_epi64x(not_sev as i64);
        let vzero = _mm256_setzero_si256();

        // Main loop: 16 entries per iteration. Singular's pattern:
        // four 4-wide AND+CMPEQ operations, OR the masks together,
        // and only branch out when *some* batch matched.
        while j + 16 <= len {
            let v1 = _mm256_loadu_si256(ptr.add(j) as *const __m256i);
            let v2 = _mm256_loadu_si256(ptr.add(j + 4) as *const __m256i);
            let v3 = _mm256_loadu_si256(ptr.add(j + 8) as *const __m256i);
            let v4 = _mm256_loadu_si256(ptr.add(j + 12) as *const __m256i);
            let a1 = _mm256_and_si256(v1, vnot_sev);
            let a2 = _mm256_and_si256(v2, vnot_sev);
            let a3 = _mm256_and_si256(v3, vnot_sev);
            let a4 = _mm256_and_si256(v4, vnot_sev);
            let c1 = _mm256_cmpeq_epi64(a1, vzero);
            let c2 = _mm256_cmpeq_epi64(a2, vzero);
            let c3 = _mm256_cmpeq_epi64(a3, vzero);
            let c4 = _mm256_cmpeq_epi64(a4, vzero);
            let m1 = _mm256_movemask_epi8(c1) as u32;
            let m2 = _mm256_movemask_epi8(c2) as u32;
            let m3 = _mm256_movemask_epi8(c3) as u32;
            let m4 = _mm256_movemask_epi8(c4) as u32;
            if (m1 | m2 | m3 | m4) != 0 {
                // Find the first matching qword across the four batches.
                // Each set qword has all 8 of its movemask bits set,
                // so trailing_zeros / 8 is the qword index.
                if m1 != 0 {
                    return j + (m1.trailing_zeros() / 8) as usize;
                }
                if m2 != 0 {
                    return j + 4 + (m2.trailing_zeros() / 8) as usize;
                }
                if m3 != 0 {
                    return j + 8 + (m3.trailing_zeros() / 8) as usize;
                }
                return j + 12 + (m4.trailing_zeros() / 8) as usize;
            }
            j += 16;
        }

        // Tail: one 4-wide batch at a time.
        while j + 4 <= len {
            let v = _mm256_loadu_si256(ptr.add(j) as *const __m256i);
            let a = _mm256_and_si256(v, vnot_sev);
            let c = _mm256_cmpeq_epi64(a, vzero);
            let m = _mm256_movemask_epi8(c) as u32;
            if m != 0 {
                return j + (m.trailing_zeros() / 8) as usize;
            }
            j += 4;
        }
    }

    // Scalar tail (0..3 elements).
    find_sev_match_scalar(sevs, not_sev, j)
}

/// Walk the basis and tail-reduce every non-redundant element against
/// the others. This is the final pass that turns a Gröbner basis
/// into **the** reduced Gröbner basis.
///
/// Strategy (mirrors Singular's `redtailBba`): for each basis index
/// `i`, extract `f = basis[i]`, temporarily mark `i` redundant, build
/// a bucket that holds only `f`'s tail (`f` without its leading
/// term), reduce the tail to normal form against the rest of the
/// basis, re-attach the original leading term, make monic, and put
/// the result back at index `i`. The `i`-redundant flag is cleared
/// unless `f`'s leading monomial was itself reducible by a *later*
/// basis element (in which case `f` really is redundant — though in
/// practice `enter_s` has already marked those cases).
///
/// This preserves the basis's leading monomials. Two successive
/// tail-reduction passes are idempotent: the output of the first
/// pass has all tail terms normal-form-reduced, so the second pass
/// finds nothing further to do.
fn tail_reduce_all(s_basis: &mut SBasis, ring: &Arc<Ring>) {
    let n = s_basis.len();
    for i in 0..n {
        if s_basis.is_redundant(i) {
            continue;
        }
        let f = s_basis.poly(i).clone();
        if f.len() <= 1 {
            // Single-term poly: nothing to tail-reduce. Still make
            // monic in case it wasn't already.
            let monic = f.monic(ring).expect("nonzero poly");
            s_basis.replace_poly(ring, i, monic);
            continue;
        }

        // Split f into leading term and tail. We'll reduce the tail
        // as a bucket, then re-attach the leading term.
        let (lc, lm) = {
            let (c, m) = f.leading().expect("nonzero");
            (c, m.clone())
        };
        let tail = f.drop_leading();

        // Mark `i` redundant during the reduction so we don't
        // accidentally reduce by ourselves.
        s_basis.set_redundant(i, true);

        let reduced_tail = reduce_tail(tail, s_basis, ring);

        // Unmark.
        s_basis.set_redundant(i, false);

        // Re-attach leading term and make monic.
        let combined = prepend_leading(lc, &lm, reduced_tail, ring);
        let monic = combined.monic(ring).expect("nonzero poly");
        s_basis.replace_poly(ring, i, monic);
    }
}

/// Reduce a tail polynomial against `s_basis` to full normal form —
/// every term is reduced, not just the leading one. Returns the
/// resulting polynomial (possibly zero).
///
/// Algorithm: hold the working polynomial in a [`KBucket`]. Peel the
/// leader at each step; if it has a divisor in the basis, run a
/// `minus_m_mult_p` that subtracts `(lc/s_lc) * (lm/s_lm) * s` from
/// the bucket (this cancels the leader and mixes the tail of the
/// multiplier back in). If it has no divisor, park the term into
/// `done` and re-scan the bucket for its new leader. The parked
/// terms accumulate in strict descending order because
/// `extract_leading` always yields the bucket's current max.
fn reduce_tail(tail: Poly, s_basis: &SBasis, ring: &Arc<Ring>) -> Poly {
    if tail.is_zero() {
        return tail;
    }
    let mut bucket = KBucket::from_poly(Arc::clone(ring), tail);
    let mut done: Vec<(Coeff, crate::monomial::Monomial)> = Vec::new();

    // clippy::while_let_loop would suggest a `while let Some((c,
    // m_ref)) = bucket.leading() { .. }`, but `bucket.leading()`
    // returns a reference tied to `bucket`, which would conflict with
    // the mutable bucket operations we need to do inside the loop.
    // The explicit `let ... else break` pattern releases the borrow
    // before we touch the bucket again.
    #[allow(clippy::while_let_loop)]
    loop {
        // Peek at the bucket's leader.
        let Some((c, m_ref)) = bucket.leading() else {
            break;
        };
        let m = m_ref.clone();
        let lm_sev = m.sev();

        // Sev pre-filter + real divisibility check.
        let sevs = s_basis.sevs();
        let redund = s_basis.redundant_flags();
        let mut divisor: Option<usize> = None;
        for idx in 0..s_basis.len() {
            if redund[idx] {
                continue;
            }
            let s_sev = sevs[idx];
            if (s_sev & !lm_sev) != 0 {
                continue;
            }
            let s_lm = s_basis
                .poly(idx)
                .leading()
                .expect("non-redundant basis element is nonzero")
                .1;
            if s_lm.divides(&m, ring) {
                divisor = Some(idx);
                break;
            }
        }
        match divisor {
            None => {
                // Term is in normal form; extract it and park.
                let (pc, pm) = bucket.extract_leading().expect("just peeked, it's there");
                debug_assert_eq!(pc, c);
                done.push((pc, pm));
            }
            Some(idx) => {
                // Reduce: bucket -= (c / s_lc) * (m / s_lm) * s.
                // Basis elements are monic (`s_lc == 1`), so
                // `(c / s_lc) == c` and we skip the Fermat inversion.
                let s = s_basis.poly(idx);
                let (s_lc, s_lm_ref) = s.leading().expect("non-redundant");
                debug_assert_eq!(s_lc, 1, "basis element should be monic");
                let _ = s_lc;
                let mult = m.div(s_lm_ref, ring).expect("divisibility checked");
                bucket.minus_m_mult_p(&mult, c, s);
            }
        }
    }

    // `done` holds the normal-form terms in strictly descending order
    // (each term came from `bucket.extract_leading`, which always
    // yields the current maximum). Use the descending-terms fast path
    // to skip the re-sort in `Poly::from_terms`.
    if done.is_empty() {
        Poly::zero()
    } else {
        Poly::from_descending_terms_unchecked(ring, done)
    }
}

/// Build a polynomial with leading term `(lc, lm)` followed by the
/// terms of `tail`. Precondition: `tail` is a canonical polynomial
/// whose every term has a monomial strictly less than `lm` under the
/// ring's ordering. `(lc, lm)` is prepended and the resulting vector
/// is already in strictly-descending order with no duplicates, so we
/// take the fast path and skip the sort.
fn prepend_leading(lc: Coeff, lm: &crate::monomial::Monomial, tail: Poly, ring: &Ring) -> Poly {
    let mut terms: Vec<(Coeff, crate::monomial::Monomial)> = Vec::with_capacity(tail.len() + 1);
    terms.push((lc, lm.clone()));
    for (c, m) in tail.iter() {
        terms.push((c, m.clone()));
    }
    Poly::from_descending_terms_unchecked(ring, terms)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::field::Field;
    use crate::monomial::Monomial;
    use crate::ordering::MonoOrder;

    fn mk_ring(nvars: u32, p: u32) -> Arc<Ring> {
        Arc::new(Ring::new(nvars, MonoOrder::DegRevLex, Field::new(p).unwrap()).unwrap())
    }

    fn mono(r: &Ring, e: &[u32]) -> Monomial {
        Monomial::from_exponents(r, e).unwrap()
    }

    #[test]
    fn empty_input_gives_empty_gb() {
        let r = mk_ring(3, 32003);
        let gb = compute_gb(Arc::clone(&r), vec![]);
        assert!(gb.is_empty());
    }

    /// Sanity check that `find_sev_match` (the dispatcher chosen at
    /// compile time based on `target_feature = "avx2"`) produces the
    /// same answer as `find_sev_match_scalar` for a range of inputs
    /// that exercise the unrolled main loop, the 4-wide tail, and
    /// the scalar tail. ADR-007.
    #[test]
    fn find_sev_match_simd_matches_scalar() {
        // Generate a deterministic pseudo-random sev array large
        // enough to span all three loop bodies in the AVX2 path
        // (16-batch main, 4-batch tail, scalar tail). Use a basic LCG
        // so the test has no external dependencies.
        let len = 200; // 12 main batches (192 entries) + 1 four-batch + 4 scalar
        let mut sevs: Vec<u64> = Vec::with_capacity(len);
        let mut state: u64 = 0x1234_5678_9abc_def0;
        for _ in 0..len {
            state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            sevs.push(state);
        }

        // Try several `not_sev` patterns that produce different match
        // densities — all-zero (every entry matches), all-set (no
        // entry matches unless its sev is zero), and a sparse mask.
        for not_sev in [
            0u64,
            !0u64,
            0x0000_0000_FFFF_FFFFu64,
            0xAAAA_AAAA_5555_5555u64,
            0x0000_0001_0000_0001u64,
        ] {
            // Try several start indices to exercise non-aligned entry
            // points into the main loop and partial-batch tails.
            for start in [0usize, 1, 7, 16, 17, 32, 96, 192, 196, 199] {
                let scalar = find_sev_match_scalar(&sevs, not_sev, start);
                let dispatch = find_sev_match(&sevs, not_sev, start);
                assert_eq!(
                    scalar, dispatch,
                    "mismatch at not_sev = {not_sev:#x}, start = {start}: \
                     scalar said {scalar}, dispatch said {dispatch}"
                );
            }
        }

        // Also explicitly check empty / single-element edge cases.
        assert_eq!(find_sev_match(&[], 0u64, 0), 0);
        assert_eq!(find_sev_match(&[5u64], 0u64, 0), 0);
        assert_eq!(find_sev_match(&[5u64], !0u64, 0), 1);
        assert_eq!(find_sev_match(&[0u64, 1u64], 1u64, 0), 0);
        assert_eq!(find_sev_match(&[0u64, 1u64], 1u64, 1), 2);
    }

    #[test]
    fn zero_input_gives_empty_gb() {
        let r = mk_ring(3, 32003);
        let gb = compute_gb(Arc::clone(&r), vec![Poly::zero()]);
        assert!(gb.is_empty());
    }

    #[test]
    fn constant_input_gives_unit_gb() {
        let r = mk_ring(3, 32003);
        let one = Poly::monomial(&r, 1, Monomial::one(&r));
        let gb = compute_gb(Arc::clone(&r), vec![one.clone()]);
        assert_eq!(gb.len(), 1);
        assert_eq!(gb[0], one);
    }

    #[test]
    fn constant_nonone_input_gives_unit_gb() {
        let r = mk_ring(3, 32003);
        let three = Poly::monomial(&r, 3, Monomial::one(&r));
        let gb = compute_gb(Arc::clone(&r), vec![three]);
        assert_eq!(gb.len(), 1);
        // Must have been made monic.
        assert_eq!(gb[0].lm_coeff(), 1);
        assert_eq!(*gb[0].leading().unwrap().1, Monomial::one(&r));
    }

    #[test]
    fn single_generator_already_gb() {
        // xy - 1 is a Gröbner basis on its own.
        let r = mk_ring(2, 32003);
        let f = Poly::from_terms(
            &r,
            vec![
                (1, mono(&r, &[1, 1])),
                (32002, mono(&r, &[0, 0])), // -1
            ],
        );
        let gb = compute_gb(Arc::clone(&r), vec![f.clone()]);
        assert_eq!(gb.len(), 1);
        assert_eq!(gb[0], f);
    }

    #[test]
    fn two_monomials_already_gb() {
        let r = mk_ring(2, 32003);
        let x = Poly::monomial(&r, 1, mono(&r, &[1, 0]));
        let y = Poly::monomial(&r, 1, mono(&r, &[0, 1]));
        let gb = compute_gb(Arc::clone(&r), vec![x.clone(), y.clone()]);
        // Coprime LMs ⇒ product criterion kills the pair. Reduced GB
        // is {x, y} (already reduced: no tail terms).
        assert_eq!(gb.len(), 2);
        // Sorted ascending: y < x in degrevlex for nvars=2.
        // degrevlex: x > y since at total-deg tie the larger-index
        // variable smaller exponent wins — x has exp (1, 0), y has
        // (0, 1), at index 1 y has exponent 1, x has 0 → x > y.
        // Ascending means y first.
        assert_eq!(gb[0], y);
        assert_eq!(gb[1], x);
    }

    #[test]
    fn cyclic3_over_f32003() {
        // x+y+z, xy+yz+zx, xyz-1 ⟶ reduced GB is
        // { x+y+z, y^2+yz+z^2, z^3-1 } (Singular reference).
        let r = mk_ring(3, 32003);
        let f1 = Poly::from_terms(
            &r,
            vec![
                (1, mono(&r, &[1, 0, 0])),
                (1, mono(&r, &[0, 1, 0])),
                (1, mono(&r, &[0, 0, 1])),
            ],
        );
        let f2 = Poly::from_terms(
            &r,
            vec![
                (1, mono(&r, &[1, 1, 0])),
                (1, mono(&r, &[0, 1, 1])),
                (1, mono(&r, &[1, 0, 1])),
            ],
        );
        let f3 = Poly::from_terms(
            &r,
            vec![(1, mono(&r, &[1, 1, 1])), (32002, mono(&r, &[0, 0, 0]))],
        );
        let gb = compute_gb(Arc::clone(&r), vec![f1, f2, f3]);

        let expected = vec![
            // x + y + z
            Poly::from_terms(
                &r,
                vec![
                    (1, mono(&r, &[1, 0, 0])),
                    (1, mono(&r, &[0, 1, 0])),
                    (1, mono(&r, &[0, 0, 1])),
                ],
            ),
            // y^2 + yz + z^2
            Poly::from_terms(
                &r,
                vec![
                    (1, mono(&r, &[0, 2, 0])),
                    (1, mono(&r, &[0, 1, 1])),
                    (1, mono(&r, &[0, 0, 2])),
                ],
            ),
            // z^3 - 1
            Poly::from_terms(
                &r,
                vec![(1, mono(&r, &[0, 0, 3])), (32002, mono(&r, &[0, 0, 0]))],
            ),
        ];
        assert_eq!(gb, expected, "cyclic-3 reduced GB mismatch");
    }

    #[test]
    fn determinism_same_input_same_output() {
        let r = mk_ring(3, 32003);
        let f1 = Poly::from_terms(
            &r,
            vec![
                (1, mono(&r, &[1, 0, 0])),
                (1, mono(&r, &[0, 1, 0])),
                (1, mono(&r, &[0, 0, 1])),
            ],
        );
        let f2 = Poly::from_terms(
            &r,
            vec![
                (1, mono(&r, &[1, 1, 0])),
                (1, mono(&r, &[0, 1, 1])),
                (1, mono(&r, &[1, 0, 1])),
            ],
        );
        let gb1 = compute_gb(Arc::clone(&r), vec![f1.clone(), f2.clone()]);
        let gb2 = compute_gb(Arc::clone(&r), vec![f1, f2]);
        assert_eq!(gb1, gb2);
    }

    #[test]
    fn input_order_invariant_cyclic3() {
        let r = mk_ring(3, 32003);
        let f1 = Poly::from_terms(
            &r,
            vec![
                (1, mono(&r, &[1, 0, 0])),
                (1, mono(&r, &[0, 1, 0])),
                (1, mono(&r, &[0, 0, 1])),
            ],
        );
        let f2 = Poly::from_terms(
            &r,
            vec![
                (1, mono(&r, &[1, 1, 0])),
                (1, mono(&r, &[0, 1, 1])),
                (1, mono(&r, &[1, 0, 1])),
            ],
        );
        let f3 = Poly::from_terms(
            &r,
            vec![(1, mono(&r, &[1, 1, 1])), (32002, mono(&r, &[0, 0, 0]))],
        );
        let gb_a = compute_gb(Arc::clone(&r), vec![f1.clone(), f2.clone(), f3.clone()]);
        let gb_b = compute_gb(Arc::clone(&r), vec![f3.clone(), f1.clone(), f2.clone()]);
        let gb_c = compute_gb(Arc::clone(&r), vec![f2, f3, f1]);
        assert_eq!(gb_a, gb_b);
        assert_eq!(gb_a, gb_c);
    }

    #[test]
    fn idempotence() {
        let r = mk_ring(3, 32003);
        let f1 = Poly::from_terms(
            &r,
            vec![
                (1, mono(&r, &[1, 0, 0])),
                (1, mono(&r, &[0, 1, 0])),
                (1, mono(&r, &[0, 0, 1])),
            ],
        );
        let f2 = Poly::from_terms(
            &r,
            vec![
                (1, mono(&r, &[1, 1, 0])),
                (1, mono(&r, &[0, 1, 1])),
                (1, mono(&r, &[1, 0, 1])),
            ],
        );
        let gb1 = compute_gb(Arc::clone(&r), vec![f1, f2]);
        let gb2 = compute_gb(Arc::clone(&r), gb1.clone());
        assert_eq!(gb1, gb2);
    }
}
